--CREATE DATABASE
CREATE DATABASE OWNER;
-- INTO DATABASE OWNER
USE OWNER;
--CREATING NEW TABLE MEMBERS
CREATE TABLE MEMBERS
(
MEMBERID INT,
FIRSTNAME VARCHAR(300),
LASTNAME VARCHAR(300),
ADDRESS VARCHAR(300),
CITY VARCHAR(300), 
);

SELECT*FROM MEMBERS;

--INSERTING INTO MEMBERS
INSERT INTO MEMBERS
--(MEMBERID,FIRSTNAME,LASTNAME,ADDRESS,CITY)
VALUES(1,'RATAN','TATA','PHASE1','BANGLORE'),(2,'GAUTAM','ADANI','PHASE2','GUJRAT'),(3,'RADHAKRISHNA','DAMANI','PHASE3','DELHI');
SELECT*FROM MEMBERS;

--ALTERTING TABLE MEMBERS USING ADD/DROP

ALTER TABLE MEMBERS
ADD COMPANY VARCHAR(300);

SELECT*FROM MEMBERS;

--ADDED COLUMN MIDDLENAME BY OWNER ->TOOLS->DESIGNER->TABLES->DBO.MEMBERS->DESIGN-> INSERT COLUMN
SELECT*FROM MEMBERS;

--SELECTING SPECIFIC COLUMNS
SELECT CITY FROM MEMBERS;
SELECT*FROM MEMBERS WHERE CITY='DELHI';
SELECT FIRSTNAME,LASTNAME FROM MEMBERS WHERE MEMBERID=3;

--UPDATING TABLE
UPDATE MEMBERS SET CITY ='GURGAON';

SELECT*FROM MEMBERS;

CREATE TABLE BUSINESS
(
MEMBERID INT,
FIRSTNAME VARCHAR(300),
LASTNAME VARCHAR(300),
CONTACT VARCHAR(300),
);

SELECT*FROM BUSINESS;

INSERT INTO BUSINESS
VALUES(1,'RITESH','AGRAWAL',9999999),(2,'BHAVISH','AGRAWAL',8888888),(3,'DEEPINDER','GOYAL',7777777);

SELECT*FROM BUSINESS;

--USING JOIN CLAUSE->INNER JOIN,RIGHT JOIN,LEFT JOIN

SELECT*FROM MEMBERS INNER JOIN BUSINESS ON MEMBERS.MEMBERID=BUSINESS.MEMBERID;

INSERT INTO BUSINESS
VALUES(4,'VVV','YYY',2222);

SELECT*FROM BUSINESS;

SELECT*FROM MEMBERS RIGHT JOIN BUSINESS ON MEMBERS.MEMBERID=BUSINESS.MEMBERID;

SELECT*FROM MEMBERS LEFT JOIN BUSINESS ON MEMBERS.MEMBERID=BUSINESS.MEMBERID;

--CREATING VIEW

CREATE VIEW
TEST_NEW AS
SELECT FIRSTNAME,LASTNAME
FROM BUSINESS;

SELECT*FROM TEST_NEW;

--DROP TABLE

DROP TABLE BUSINESS;
SELECT*FROM BUSINESS;

DROP TABLE MEMBERS;
SELECT*FROM BUSINESS;

USE MASTER;
GO
ALTER DATABASE OWNER
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
DROP DATABASE OWNER;